@admin-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzIyODI0MDZ9._pM3gd0BBPeYotH7JUr30o8bHesIWA4TUpMJ9d-_1xo
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzIyODAzMjZ9.hxDI56taAHOZ7fLN75WIpy44meK6oRs9HLJB_CIu0cw

### Products Index
GET http://localhost:3000/products.json

### Products Create
POST http://localhost:3000/products.json
Authorization: Bearer {{admin-jwt}}
Content-Type: application/json

{
  "name": "Giraffe",
  "price": 5,
  "description": "YET ANOTHER ONE.",
  "image": "https://lh3.googleusercontent.com/-Ruw1ZgP_38Q/V4Js2LvrpaI/AAAAAAAACSU/gBv5ZjTp4XE/s640/blogger-image--780847963.jpg"
}

### Products Show 
GET http://localhost:3000/products/1.json

### Products Update
PATCH http://localhost:3000/products/9.json
Authorization: Bearer {{admin-jwt}}
Content-Type: application/json

{
  "description": "NO MORE GIRAFFE!"
}

### Products Destroy
DELETE http://localhost:3000/products/9.json
Authorization: Bearer {{admin-jwt}}

### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sara",
  "email": "s@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSIONS CREATE (log in)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "s@example.com",
  "password": "password"
}

### ORDERS Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}



### ORDERS SHOW 
GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}


### ORDERS CREATE
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 4
  }



