@admin-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODA5NzE0OTZ9.iGBCVQu-utiuYtQutcB_FzYifxLd3yVg10o6oP0PFkc
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzIyODAzMjZ9.hxDI56taAHOZ7fLN75WIpy44meK6oRs9HLJB_CIu0cw

### Products Index
GET http://localhost:3000/products.json

### Products Create
POST http://localhost:3000/products.json
Authorization: Bearer {{admin-jwt}}
Content-Type: application/json

{
  "name": "Giraffe",
  "price": 5,
  "description": "UGH YET ANOTHER ONE.",
  "image": "https://lh3.googleusercontent.com/-Ruw1ZgP_38Q/V4Js2LvrpaI/AAAAAAAACSU/gBv5ZjTp4XE/s640/blogger-image--780847963.jpg"
}

### Products Show 
GET http://localhost:3000/products/1.json

### Products Update
PATCH http://localhost:3000/products/6.json
Authorization: Bearer {{admin-jwt}}
Content-Type: application/json

{
  "description": "LUCKY"
}

### Products Destroy
DELETE http://localhost:3000/products/6.json
Authorization: Bearer {{admin-jwt}}

### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sara",
  "email": "s@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSIONS CREATE (log in)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "s@example.com",
  "password": "password"
}

#will this need to be product in views/index if i only have one?
### ORDERS Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{admin-jwt}}


#will this need to be product in views/show if i only have one?
### ORDERS SHOW 
GET http://localhost:3000/orders/6.json
Authorization: Bearer {{admin-jwt}}


### ORDERS CREATE
POST http://localhost:3000/orders.json
Authorization: Bearer {{admin-jwt}}
Content-Type: application/json


### CARTED PRODUCTS INDEX
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{admin-jwt}}


### Carted Products CREATE

POST http://localhost:3000/carted_products.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}

{
  "product_id": 1,
  "quantity": 4
}

### Carted Products DESTROY

DELETE http://localhost:3000/carted_products/2.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}


