@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzIyNjk3NjN9.dOHak_lLsk9fjVb7WsXXCQFeb2PKnzl933DRzoLUHKw

### Products Index
GET http://localhost:3000/products.json

### Products Create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Giraffe",
  "price": 5,
  "description": "Not the worst giraffe pattern out there.",
  "image": "https://lh3.googleusercontent.com/-Ruw1ZgP_38Q/V4Js2LvrpaI/AAAAAAAACSU/gBv5ZjTp4XE/s640/blogger-image--780847963.jpg"
}

### Products Show 
GET http://localhost:3000/products/1.json

### Products Update
PATCH http://localhost:3000/products/5.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "description": "ANOTHER GIRAFFE!"
}

### Products Destroy
DELETE http://localhost:3000/products/5.json
Authorization: Bearer {{jwt}}

### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSIONS CREATE (log in)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}